### ISSUE TITLE
CI/CD 구성

### ISSUE THREAD

**Issue by neizzz** [neizzz/hmz#17]

**Comment by neizzz** [comment]
~~* [ ] source map for development build~~
~~* [ ] check auto deploy from webhook~~
~~* [ ] jenkins 서버 구축~~
~~* [ ] jenkins CI/CD 파이프라인 구축~~

**Comment by neizzz** [comment]
circleci example

```yaml
# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: deps:node:.
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: echo 'replace me with real tests!' && false
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
```
